### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by RainbowRui** [pvnieo/3d-utils#1]
After I compile SHOT following your provided procedure and import shot.shot, I receive an Import Error.
`ImportError: dynamic module does not define module export function (PyInit_shot)`
What is wrong? Thanks!

**Comment by pvnieo** [comment]
which python version are you using?

**Comment by RainbowRui** [comment]
> which python version are you using?

It is 3.8.8.

**Comment by RainbowRui** [comment]
> which python version are you using?

Thanks for you quick reply!

**Comment by pvnieo** [comment]
that's weird!
did you installed the latest versions of pybind and pcl as described in the readme?

**Comment by RainbowRui** [comment]
Of course, the versions of pybind (use git to obtain) and pcl is latest!

**Comment by RainbowRui** [comment]
> that's weird!
> did you installed the latest versions of pybind and pcl as described in the readme?

I install pytest 6.2.2 in anaconda virtual environment. Build, make and install Pybind11 2.6.2 following your described. Then, use apt to install libpcl-dev (version: 1.8.1+dfsg1-2ubuntu2.18.04.1). At last, compile SHOT as you described.

**Comment by RainbowRui** [comment]
> that's weird!
> did you installed the latest versions of pybind and pcl as described in the readme?

Is it related to my use of anaconda?

**Comment by RainbowRui** [comment]
> that's weird!
> did you installed the latest versions of pybind and pcl as described in the readme?

I install pytest 6.2.2, pybind11 2.6.2, pcl 1.11.1 and cmake 3.19.6 in anaconda virtual environment. However, I still get the same error while importing shot.

**Comment by pvnieo** [comment]
Hi,
Sorry, I don't know,  I have never faced this error before!
Please let me know if you have any updates!

**Comment by RainbowRui** [comment]
> Hi,
> Sorry, I don't know, I have never faced this error before!
> Please let me know if you have any updates!

You are welcome! If I have any updates, I will tell you. Thanks for your contribution and quick reply!

**Comment by RainbowRui** [comment]
> Hi,
> Sorry, I don't know, I have never faced this error before!
> Please let me know if you have any updates!

Finally, I solve it after installing pybind11 under the anaconda virtual environment.

**Comment by pvnieo** [comment]
Hi,
Good to hear that you solved your issue!
Is `shot` working now?

**Comment by RainbowRui** [comment]
> Hi,
> Good to hear that you solved your issue!
> Is `shot` working now?

Yes! Thanks for your reply!

**Comment by pvnieo** [comment]
cool, closing the issue!
feel free to open it if you have further questions!

**Comment by wooriel** [comment]
I also have the same error as I am trying to run shot on FMNet.
I had versions that satisfy the requirements. I don't know if it depends on where I install pybind11, but if I resolve this issue, I will write how specifically solved it..
