### ISSUE TITLE
Cannot execute make command for the pybind11 package on windows

### ISSUE THREAD

**Issue by wajdan846** [pvnieo/3d-utils#2]
The command

`cmake ..`

is executed successfully with the VS 2019 compiler on Windows but the makefile is not generated and consequently the make command is unsuccessful with the error

" make: *** No targets specified and no makefile found.  Stop. "

**Comment by pvnieo** [comment]
Hi @wajdan846 

Sorry for the late reply, but I don't have any experience using Windows :( 

I hope you have already found a solution to your problem, if so, don't hesitate to post it in this thread!

**Comment by pvnieo** [comment]
Closing the issue, please feel free to open it if you have further questions!
