### ISSUE TITLE
Dynamic module doesnot define  module export function

### ISSUE THREAD

**Issue by wajdan846** [pvnieo/3d-utils#3]
I'm simply running preprocessing.py and getting this error after executing make for shot util

ImportError: dynamic module does not define module export function (PyInit_shot

**Comment by pvnieo** [comment]
Hi @wajdan846 

The source could be multiple things, and some of them are related to your env, can you give more description?

**Comment by pvnieo** [comment]
Closing the issue, please feel free to reopen it if you have further questions!
